# -*- coding: utf-8 -*-
"""InputBands_Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GDdzf1xWedln_Te-J-WTUPctz2cW-t3
"""

import ee
ee.Authenticate()
ee.Initialize(project='macedo-lab-general-9051')

area = ee.FeatureCollection('projects/ksolvik-misc/assets/Lim_Raisg')
amazonBounds = area.geometry().simplify(1000) #I had to simplify the area because stratified sampling was failing on the initial complex area
embeddingsCol = ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')
# TODO: Include distance to pasture separate from general human activities
distancePreCalculee = ee.Image('projects/columbia-research-project/assets/distanceHumanActivities_Amazon_100m_2017-2023')
# TODO: Include distance to indigenous protected areas specificially
distancePreCalculee2 = ee.Image('projects/columbia-research-project/assets/distanceProtectedAreas_Amazon_100m_v2')
distancePreCalculee3 = ee.Image('projects/columbia-research-project/assets/distanceProtectedAreas_Amazon_100m')
viirs_burnedYears = ee.Image('projects/columbia-research-project/assets/VIIRS_Target_2019-2024')

def addCWD(era5LandImage):
    """Calculate CWD from single image"""
    era5LandImageCWD = (era5LandImage
        .addBands(
            (era5LandImage.select('total_precipitation_sum')
                  .subtract(era5LandImage.select('total_evaporation_sum').multiply(-1))
             ).rename('cwd')
        )
    )
    return era5LandImageCWD

def create_inputBands(target_year):
    targetYear = ee.Number(target_year)
    dataYear = targetYear.subtract(1)
    prevDataYear = targetYear.subtract(2)

    ### Input Bands

    #Embeddings from 2Y ago
    inputs = (embeddingsCol
              .filterDate(ee.Date.fromYMD(prevDataYear, 1, 1), ee.Date.fromYMD(dataYear, 1, 1))
              .filterBounds(amazonBounds)
              .mosaic())

    # Target VIIRS Hot Spots
    # TODO: Update with new images once ready. Include prev year of data as an input
    class_band = ee.String('class_').cat(targetYear.format('%d'))
    conf_band = ee.String('conf_').cat(targetYear.format('%d'))
    type_band = ee.String('type_').cat(targetYear.format('%d'))

    target = viirs_burnedYears.select(
        [class_band, conf_band, type_band],
        ['class', 'confidence', 'fire_type']
    )

    #Distances
    distanceBandName = ee.String('distance_').cat(dataYear.format('%d'))
    distanceAuxZonesHumaines = distancePreCalculee.select(distanceBandName).rename('DistanceHumanActivities')
    distanceStrictProtectedAreas = distancePreCalculee2.select('Distance_StrictProtected').rename('DistanceStrictProtectedAreas')
    distanceSustainableUseProtectedAreas = distancePreCalculee2.select('Distance_SustainableUse').rename('DistanceSustainableUseProtectedAreas')
    distanceAllProtectedAreas = distancePreCalculee3.select('distance_wdpa').rename('DistanceAllProtectedAreas')

    # Deforestation
    # TODO: When we run future predictions, we won't have the latest annual deforestation
    # One option is to update with the GLAD-L alerts dataset: 
    # https://glad.umd.edu/dataset/glad-forest-alerts
    hansen = ee.Image('UMD/hansen/global_forest_change_2025_v1_13')
    targetYearHansen = targetYear.subtract(2000)
    hansenMasked = hansen.mask(
        hansen.select('lossyear').lte(targetYearHansen)
        ).select(['treecover2000', 'loss', 'lossyear'])

    # ERA5 climate data
    startMeteo = ee.Date.fromYMD(prevDataYear, 11, 1)
    endMeteo = ee.Date.fromYMD(dataYear, 11, 1)

    # ERA5 Ag - Daily, with temp vars and more
    era5Ag = (ee.ImageCollection('projects/climate-engine-pro/assets/ce-ag-era5-v2/daily')
            .filterDate(startMeteo, endMeteo))
    era5AgSelect = era5Ag.select(
            ['Precipitation_Flux', 'Temperature_Air_2m_Mean_24h', 'Temperature_Air_2m_Max_24h',
             'Temperature_Air_2m_Min_24h', 'Vapour_Pressure_Deficit_at_Maximum_Temperature']
            )
    months = ee.List.sequence(1, 12)
    # IMPORTANT: Must already be filtered to a single year
    era5AgMonthly = ee.ImageCollection.fromImages(
        months.map(lambda m: 
                   era5AgSelect.filter(ee.Filter.calendarRange(m, m, 'month'))
                   .mean()
        )
    )
    era5AgStats = (era5AgMonthly.mean().addBands(
                   era5AgMonthly.reduce(ee.Reducer.minMax()))
                   )

    # ERA5Land products - higher res, includes evaporation
    era5Land = (ee.ImageCollection('ECMWF/ERA5_LAND/MONTHLY_AGGR')
            .filterDate(startMeteo, endMeteo))
    era5LandCWD = (era5Land.select(
        ['total_evaporation_sum', 'total_precipitation_sum']
        ).map(addCWD)
        )
    era5LandStats = (era5LandCWD.mean().addBands(
                     era5LandCWD.reduce(ee.Reducer.minMax()))
                     )

    modVI = (ee.ImageCollection('MODIS/061/MOD13A1')
                .filterDate(startMeteo, endMeteo)
                .select(['NDVI','EVI']).merge(
                    (ee.ImageCollection('MODIS/061/MYD13A1')
                    .filterDate(startMeteo, endMeteo)
                    .select(['NDVI','EVI'])
                   ))
            ).mean()

    # World Population
    landscanCol = ee.ImageCollection("projects/sat-io/open-datasets/ORNL/LANDSCAN_GLOBAL")
    population = (landscanCol.filterDate(startMeteo, endMeteo)
                  .select('b1')
                  .mosaic()
                  .unmask(0)
                  .rename('Population_Density'))

    # Night Lights
    nightLightsCol = ee.ImageCollection("NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG")
    nightLights = (nightLightsCol.filterDate(startMeteo, endMeteo)
                   .select('avg_rad')
                   .mean()
                   .unmask(0)
                   .rename('Nighttime_Lights'))

    # Topography
    terrain = ee.Terrain.products(ee.Image('USGS/SRTMGL1_003'))
    elevation = terrain.select('elevation').rename('Elevation')
    slope = terrain.select('slope').rename('Slope')

    # Accessibility to cities
    accessToCities =  (ee.Image('projects/malariaatlasproject/assets/accessibility/accessibility_to_cities/2015_v1_0')
                       .select('accessibility'))

    # TODO: Add VIIRS NRT record for past 5 years based on Suomi NPP (but still keep MODIS):
    # https://gee-community-catalog.org/projects/firms_vector/
    # Fire memory MODIS (I don't know if it's a good idea to keep MODIS here, I might have to change it to VIIRS Hot Spots too)
    startMemoryDate = ee.Date.fromYMD(targetYear.subtract(5), 1, 1)
    endMemoryDate = endMeteo

    modisMemoryCol = (ee.ImageCollection('MODIS/061/MCD64A1')
                      .filterDate(startMemoryDate, endMemoryDate)
                      .filterBounds(amazonBounds)
                      .select('BurnDate'))

    fireMemory = modisMemoryCol.max().gt(0).unmask(0).rename('Fire_Memory_5y')

    #TargetYear
    yearBand = ee.Image.constant(targetYear).rename('Target_Year')

    # Fusion
    imageFinale = (inputs.addBands(target)
        .addBands(distanceStrictProtectedAreas)
        .addBands(distanceSustainableUseProtectedAreas)
        .addBands(distanceAllProtectedAreas)
        .addBands(distanceAuxZonesHumaines)
        .addBands(era5AgStats)
        .addBands(era5LandStats)
        .addBands(modVI)
        .addBands(accessToCities)
        .addBands(hansenMasked)
        .addBands(population)
        .addBands(nightLights)
        .addBands(elevation)
        .addBands(slope)
        .addBands(fireMemory)
        .addBands(yearBand))

    return imageFinale, target
