# -*- coding: utf-8 -*-
"""InputBands_Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GDdzf1xWedln_Te-J-WTUPctz2cW-t3
"""

import ee
ee.Authenticate()
ee.Initialize(project='columbia-research-project')

area = ee.FeatureCollection('projects/ksolvik-misc/assets/Lim_Raisg')
amazonBounds = area.geometry().simplify(1000) #I had to simplify the area because stratified sampling was failing on the initial complex area
embeddingsCol = ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')

distancePreCalculee = ee.Image('projects/columbia-research-project/assets/distanceHumanActivities_Amazon_100m_2017-2023')
distancePreCalculee2 = ee.Image('projects/columbia-research-project/assets/distanceProtectedAreas_Amazon_100m_v2')
distancePreCalculee3 = ee.Image('projects/columbia-research-project/assets/distanceProtectedAreas_Amazon_100m')
distancePreCalculee4 = ee.Image('projects/columbia-research-project/assets/DistanceIndigenousAreas_Amazon_100m')
distancePreCalculee5 = ee.Image('projects/columbia-research-project/assets/DistancePastures_Amazon_100m')
distanceIndigenous = distancePreCalculee4.select('distance_IndigenousAreas').rename('DistanceIndigenousAreas')



def addCWD(era5LandImage):
    """Calculate CWD from single image"""
    era5LandImageCWD = (era5LandImage
        .addBands(
            (era5LandImage.select('total_precipitation_sum')
                  .subtract(era5LandImage.select('total_evaporation_sum').multiply(-1))
             ).rename('cwd')
        )
    )
    return era5LandImageCWD

def create_inputBands(target_year):
    targetYear = ee.Number(target_year)
    dataYear = targetYear.subtract(1)

    ### Input Bands

    #Embeddings from data year
    inputs = (embeddingsCol
              .filterDate(ee.Date.fromYMD(dataYear, 1, 1), ee.Date.fromYMD(targetYear, 1, 1))
              .filterBounds(amazonBounds)
              .mosaic())

    # Target VIIRS Hot Spots
    viirs_path = f'projects/ksolvik-misc/assets/amazon_fire_dashboard/rasters/amazon_nrt_fire_{target_year}_raster'
    viirs_target = ee.Image(viirs_path)
    fireSize_band = 'b1'
    type_band = 'b2'
    conf_band = 'b3'

    target = (viirs_target.select(fireSize_band)
                 .gt(0)
                 .unmask(0)
                 .rename('class')
                 .toInt()
                 .clip(amazonBounds))


    fireData = viirs_target.select(
        [fireSize_band, type_band, conf_band],
        ['fireSize', 'fire_type', 'confidence']
    ).toInt()

    #Distances
    target_year_int = int(target_year)
    data_year_int = target_year_int - 1
    distancePastures = distancePreCalculee5.select(f'distance_{target_year_int}').rename('DistancePastures')
    distanceBandName = f'distance_{data_year_int}'
    distanceAuxZonesHumaines = distancePreCalculee.select(distanceBandName).rename('DistanceHumanActivities')

    distanceStrictProtectedAreas = distancePreCalculee2.select('Distance_StrictProtected').rename('DistanceStrictProtectedAreas')
    distanceSustainableUseProtectedAreas = distancePreCalculee2.select('Distance_SustainableUse').rename('DistanceSustainableUseProtectedAreas')
    distanceAllProtectedAreas = distancePreCalculee3.select('distance_wdpa').rename('DistanceAllProtectedAreas')

    # Deforestation
    hansen = ee.Image('UMD/hansen/global_forest_change_2025_v1_13').select(['treecover2000', 'loss', 'lossyear']).rename(['hansen_treecover2000', 'hansen_loss', 'hansen_lossyear']).unmask(0);

    glad_alertdate = ee.Image('projects/glad/S2alert/alertDate').rename('glad_alertdate').unmask(0);

    # ERA5 climate data
    startMeteo = ee.Date.fromYMD(dataYear, 1, 1)
    endMeteo = ee.Date.fromYMD(dataYear, 12, 31) #Changed this timelapse too, hope it still works

    # ERA5 Ag - Daily, with temp vars and more
    era5Ag = (ee.ImageCollection('projects/climate-engine-pro/assets/ce-ag-era5-v2/daily')
            .filterDate(startMeteo, endMeteo))
    era5AgSelect = era5Ag.select(
            ['Precipitation_Flux', 'Temperature_Air_2m_Mean_24h', 'Temperature_Air_2m_Max_24h',
             'Temperature_Air_2m_Min_24h', 'Vapour_Pressure_Deficit_at_Maximum_Temperature']
            )
    months = ee.List.sequence(1, 12)
    # IMPORTANT: Must already be filtered to a single year
    era5AgMonthly = ee.ImageCollection.fromImages(
        months.map(lambda m: 
                   era5AgSelect.filter(ee.Filter.calendarRange(m, m, 'month'))
                   .mean()
        )
    )
    era5AgStats = (era5AgMonthly.mean().addBands(
                   era5AgMonthly.reduce(ee.Reducer.minMax()))
                   )

    # ERA5Land products - higher res, includes evaporation
    era5Land = (ee.ImageCollection('ECMWF/ERA5_LAND/MONTHLY_AGGR')
            .filterDate(startMeteo, endMeteo))
    era5LandCWD = (era5Land.select(
        ['total_evaporation_sum', 'total_precipitation_sum']
        ).map(addCWD)
        )
    era5LandStats = (era5LandCWD.mean().addBands(
                     era5LandCWD.reduce(ee.Reducer.minMax()))
                     )

    modVI = (ee.ImageCollection('MODIS/061/MOD13A1')
                .filterDate(startMeteo, endMeteo)
                .select(['NDVI','EVI']).merge(
                    (ee.ImageCollection('MODIS/061/MYD13A1')
                    .filterDate(startMeteo, endMeteo)
                    .select(['NDVI','EVI'])
                   ))
            ).mean()

    # World Population
    landscanCol = ee.ImageCollection("projects/sat-io/open-datasets/ORNL/LANDSCAN_GLOBAL")
    population = (landscanCol.filterDate(startMeteo, endMeteo)
                  .select('b1')
                  .mosaic()
                  .unmask(0)
                  .rename('Population_Density'))

    # Night Lights
    nightLightsCol = ee.ImageCollection("NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG")
    nightLights = (nightLightsCol.filterDate(startMeteo, endMeteo)
                   .select('avg_rad')
                   .mean()
                   .unmask(0)
                   .rename('Nighttime_Lights'))

    # Topography
    terrain = ee.Terrain.products(ee.Image('USGS/SRTMGL1_003'))
    elevation = terrain.select('elevation').rename('Elevation')
    slope = terrain.select('slope').rename('Slope')

    # Accessibility to cities
    accessToCities =  (ee.Image('projects/malariaatlasproject/assets/accessibility/accessibility_to_cities/2015_v1_0')
                       .select('accessibility'))

    # MODIS Fire memory
    startMemoryDate = ee.Date.fromYMD(targetYear.subtract(5), 1, 1)
    endMemoryDate = endMeteo

    modisMemoryCol = (ee.ImageCollection('MODIS/061/MCD64A1')
                      .filterDate(startMemoryDate, endMemoryDate)
                      .filterBounds(amazonBounds)
                      .select('BurnDate'))
    MODISfireMemory = modisMemoryCol.max().gt(0).unmask(0).rename('MODIS_Fire_Memory_5y')

    #VIIRS Fire Memory

    viirs_start_date = ee.Date.fromYMD(dataYear.subtract(4), 1, 1)
    viirs_end_date = ee.Date.fromYMD(dataYear, 12, 31)

    fiveYFires = (ee.ImageCollection('projects/ksolvik-misc/assets/viirs_snpp_archive').filterDate(viirs_start_date, viirs_end_date))

    def transform_to_year(img):

        imageYear = ee.Number.parse(img.date().format('YYYY'))
        masque_feu = img.gt(0)

        return ee.Image.constant(imageYear).rename('fire_year').toInt().updateMask(masque_feu)

    VIIRSfireMemory = fiveYFires.map(transform_to_year).max().unmask(0).rename('VIIRS_Fire_Memory_5y')

    #TargetYear
    yearBand = ee.Image.constant(targetYear).rename('Target_Year')

    # Fusion
    imageFinale = (inputs.addBands(target)
        .addBands(fireData)
        .addBands(distanceStrictProtectedAreas)
        .addBands(distanceSustainableUseProtectedAreas)
        .addBands(distanceAllProtectedAreas)
        .addBands(distanceAuxZonesHumaines)
        .addBands(distanceIndigenous)
        .addBands(distancePastures)
        .addBands(era5AgStats)
        .addBands(era5LandStats)
        .addBands(modVI)
        .addBands(accessToCities)
        .addBands(hansen)
        .addBands(glad_alertdate)
        .addBands(population)
        .addBands(nightLights)
        .addBands(elevation)
        .addBands(slope)
        .addBands(MODISfireMemory)
        .addBands(VIIRSfireMemory)
        .addBands(yearBand))

    return imageFinale, target
