# -*- coding: utf-8 -*-
"""InputBands_Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GDdzf1xWedln_Te-J-WTUPctz2cW-t3
"""

import ee
ee.Authenticate()
from aic_risk_modeling.preprocess import download_clim_indices
ee.Initialize(project='macedo-lab-general-9051')

area = ee.FeatureCollection('projects/ksolvik-misc/assets/Lim_Raisg')
amazonBounds = area.geometry().simplify(1000) #I had to simplify the area because stratified sampling was failing on the initial complex area
embeddingsCol = ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')
distancePreCalculee = ee.Image('projects/columbia-research-project/assets/distanceHumanActivities_Amazon_100m_2017-2023')
distancePreCalculee2 = ee.Image('projects/columbia-research-project/assets/distanceProtectedAreas_Amazon_100m_v2')
distancePreCalculee3 = ee.Image('projects/columbia-research-project/assets/distanceProtectedAreas_Amazon_100m')
viirs_burnedYears = ee.Image('projects/columbia-research-project/assets/VIIRS_Target_2019-2024')

def create_inputBands(target_year):
    targetYear = ee.Number(target_year)
    dataYear = targetYear.subtract(1)
    prevDataYear = targetYear.subtract(2)

    ### Input Bands

    #Embeddings from 2Y ago
    inputs = (embeddingsCol
              .filterDate(ee.Date.fromYMD(prevDataYear, 1, 1), ee.Date.fromYMD(dataYear, 1, 1))
              .filterBounds(amazonBounds)
              .mosaic())

    # Target VIIRS Hot Spots
    class_band = ee.String('class_').cat(targetYear.format('%d'))
    conf_band = ee.String('conf_').cat(targetYear.format('%d'))
    type_band = ee.String('type_').cat(targetYear.format('%d'))

    target = viirs_burnedYears.select(
        [class_band, conf_band, type_band],
        ['class', 'confidence', 'fire_type']
    )

    #Distances
    distanceBandName = ee.String('distance_').cat(dataYear.format('%d'))
    distanceAuxZonesHumaines = distancePreCalculee.select(distanceBandName).rename('DistanceHumanActivities')
    distanceStrictProtectedAreas = distancePreCalculee2.select('Distance_StrictProtected').rename('DistanceStrictProtectedAreas')
    distanceSustainableUseProtectedAreas = distancePreCalculee2.select('Distance_SustainableUse').rename('DistanceSustainableUseProtectedAreas')
    distanceAllProtectedAreas = distancePreCalculee3.select('distance_wdpa').rename('DistanceAllProtectedAreas')

    # Deforestation
    hansen = ee.Image('UMD/hansen/global_forest_change_2025_v1_13')
    targetYearHansen = targetYear.subtract(2000)
    hansenMasked = hansen.mask(
        hansen.select('lossyear').lte(targetYearHansen)
        ).select(['treecover2000', 'loss', 'lossyear'])

    # Evapotranspiration
    startMeteo = ee.Date.fromYMD(dataYear, 1, 1)
    endMeteo = ee.Date.fromYMD(targetYear, 1, 1)

    era5Land = (ee.ImageCollection('ECMWF/ERA5_LAND/MONTHLY_AGGR') #Replaces terraClimate
                .filterDate(startMeteo, endMeteo))

    Evapotranspiration = (era5Land.select('total_evaporation_sum')
                               .sum()
                               .multiply(-1) #To keep positive values, don't know if useful
                               .unmask(0)
                               .rename('Evapotranspiration'))

    # World Population
    landscanCol = ee.ImageCollection("projects/sat-io/open-datasets/ORNL/LANDSCAN_GLOBAL")
    population = (landscanCol.filterDate(ee.Date.fromYMD(dataYear, 1, 1), ee.Date.fromYMD(targetYear, 1, 1))
                  .select('b1')
                  .mosaic()
                  .unmask(0)
                  .rename('Population_Density'))

    # Night Lights
    nightLightsCol = ee.ImageCollection("NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG")
    nightLights = (nightLightsCol.filterDate(ee.Date.fromYMD(dataYear, 1, 1), ee.Date.fromYMD(targetYear, 1, 1))
                   .select('avg_rad')
                   .mean()
                   .unmask(0)
                   .rename('Nighttime_Lights'))

    # Topography
    terrain = ee.Terrain.products(ee.Image('USGS/SRTMGL1_003'))
    elevation = terrain.select('elevation').rename('Elevation')
    slope = terrain.select('slope').rename('Slope')

    # Fire memory MODIS (I don't know if it's a good idea to keep MODIS here, I might have to change it to VIIRS Hot Spots too)
    startMemoryDate = ee.Date.fromYMD(targetYear.subtract(5), 1, 1)
    endMemoryDate = ee.Date.fromYMD(targetYear, 1, 1)

    modisMemoryCol = (ee.ImageCollection('MODIS/061/MCD64A1')
                      .filterDate(startMemoryDate, endMemoryDate)
                      .filterBounds(amazonBounds)
                      .select('BurnDate'))

    fireMemory = modisMemoryCol.max().gt(0).unmask(0).rename('Fire_Memory_5y')

    #TargetYear
    yearBand = ee.Image.constant(targetYear).rename('Target_Year')

    # Fusion
    imageFinale = (inputs.addBands(target)
        .addBands(distanceStrictProtectedAreas)
        .addBands(distanceSustainableUseProtectedAreas)
        .addBands(distanceAllProtectedAreas)
        .addBands(distanceAuxZonesHumaines)
        .addBands(Evapotranspiration)
        .addBands(hansenMasked)
        .addBands(population)
        .addBands(nightLights)
        .addBands(elevation)
        .addBands(slope)
        .addBands(fireMemory)
        .addBands(yearBand))

    return imageFinale, target
