# -*- coding: utf-8 -*-
"""InputBands_Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GDdzf1xWedln_Te-J-WTUPctz2cW-t3
"""

import ee
ee.Authenticate()
from aic_risk_modeling.preprocess import download_clim_indices
ee.Initialize(project='macedo-lab-general-9051')

area = ee.FeatureCollection('projects/ksolvik-misc/assets/Lim_Raisg')
amazonBounds = area.geometry().simplify(1000) #I had to simplify the area because stratified sampling was failing on the initial complex area
embeddingsCol = ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')
mapbiomas = ee.Image('projects/mapbiomas-public/assets/brazil/fire/collection4/mapbiomas_fire_collection4_annual_burned_v1')
distancePreCalculee = ee.Image('projects/columbia-research-project/assets/distanceHumanActivities_Amazon_100m_2017-2023')
distancePreCalculee2 = ee.Image('projects/columbia-research-project/assets/distanceProtectedAreas_Amazon_100m_v2')
distancePreCalculee3 = ee.Image('projects/columbia-research-project/assets/distanceProtectedAreas_Amazon_100m')
viirs_all_years = ee.Image('projects/columbia-research-project/assets/VIIRS_Target_2019-2024')

startYears = ee.List([2019, 2020, 2021, 2022, 2023]) #Delete 2022 to have the training set for predicting on 2023, etc...

def create_inputBands(year):
    currentYear = ee.Number(year)
    nextYear = currentYear.add(1)
    previousYear = currentYear.subtract(1)

    ### Input Bands ###

    #Embeddings from 2Y ago
    inputs = (embeddingsCol
              .filterDate(ee.Date.fromYMD(previousYear, 1, 1), ee.Date.fromYMD(currentYear, 1, 1))
              .filterBounds(amazonBounds)
              .mosaic())

    startDate = ee.Date.fromYMD(nextYear, 1, 1)
    endDate = ee.Date.fromYMD(nextYear.add(1), 1, 1)

    # Target VIIRS Hot Spots
    band_name = ee.String('year_').cat(currentYear.format('%d'))
    target = viirs_all_years.select([band_name], ['class'])

    # ONI (El Nino pattern)
    df_oni = download_clim_indices("oni", year_start=2015, year_end=2024)
    df_oni['year'] = df_oni.index.year
    df_oni['quarter'] = df_oni.index.quarter

    quarterly_oni = df_oni.groupby(['year', 'quarter'])['metric'].mean().unstack()

    oni_dict_python = {}
    for annee_idx, row in quarterly_oni.iterrows():
        oni_dict_python[str(annee_idx)] = [round(val, 1) for val in row.values]

    oniQuarters = ee.Dictionary(oni_dict_python)

    currentOniValues = ee.List(oniQuarters.get(currentYear.format('%d')))
    prevOniValues = ee.List(oniQuarters.get(previousYear.format('%d')))

    oniImageCurrentYear = (ee.Image.constant(currentOniValues)
        .rename(['ONI_Q1_curr', 'ONI_Q2_curr', 'ONI_Q3_curr', 'ONI_Q4_curr']))

    oniImagePrevYear = (ee.Image.constant(prevOniValues)
        .rename(['ONI_Q1_prev', 'ONI_Q2_prev', 'ONI_Q3_prev', 'ONI_Q4_prev']))

    #Distances
    distanceBandName = ee.String('distance_').cat(currentYear.format('%d'))
    distanceAuxZonesHumaines = distancePreCalculee.select(distanceBandName).rename('DistanceHumanActivities')
    distanceStrictProtectedAreas = distancePreCalculee2.select('Distance_StrictProtected').rename('DistanceStrictProtectedAreas')
    distanceSustainableUseProtectedAreas = distancePreCalculee2.select('Distance_SustainableUse').rename('DistanceSustainableUseProtectedAreas')
    distanceAllProtectedAreas = distancePreCalculee3.select('distance_wdpa').rename('DistanceAllProtectedAreas')

    # WIND
    startDry = ee.Date.fromYMD(currentYear, 8, 1)
    endDry = ee.Date.fromYMD(currentYear, 10, 31)

    era5Wind = (ee.ImageCollection('ECMWF/ERA5_LAND/MONTHLY_AGGR')
        .filterDate(startDry, endDry)
        .mean())

    windSpeed = era5Wind.expression(
        'sqrt(u**2 + v**2)', {
            'u': era5Wind.select('u_component_of_wind_10m'),
            'v': era5Wind.select('v_component_of_wind_10m')
        }
    ).unmask(2).rename('Wind_Speed_DrySeason')

    # Deforestation
    hansen = ee.Image('UMD/hansen/global_forest_change_2025_v1_13')
    yearHansen = currentYear.subtract(2000)

    recentDeforestation = (hansen.select('lossyear')
        .gte(yearHansen.subtract(1))
        .And(hansen.select('lossyear').lte(yearHansen))
        .unmask(0)
        .rename('Recent_Deforestation'))

    # Evapotranspiration
    terraClimate = (ee.ImageCollection('IDAHO_EPSCOR/TERRACLIMATE')
        .filterDate(startDry, endDry)
        .select('aet')
        .mean())

    etSafe = terraClimate.multiply(0.1).unmask(0).rename('Evapotranspiration')

    # World Population
    landscanCol = ee.ImageCollection("projects/sat-io/open-datasets/ORNL/LANDSCAN_GLOBAL")
    population = (landscanCol.filterDate(ee.Date.fromYMD(currentYear, 1, 1), ee.Date.fromYMD(nextYear, 1, 1))
                  .select('b1')
                  .mosaic()
                  .unmask(0)
                  .rename('Population_Density'))

    # Night Lights
    nightLightsCol = ee.ImageCollection("NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG")
    nightLights = (nightLightsCol.filterDate(ee.Date.fromYMD(currentYear, 1, 1), ee.Date.fromYMD(nextYear, 1, 1))
                   .select('avg_rad')
                   .mean()
                   .unmask(0)
                   .rename('Nighttime_Lights'))

    # Topography
    terrain = ee.Terrain.products(ee.Image('USGS/SRTMGL1_003'))
    elevation = terrain.select('elevation').rename('Elevation')
    slope = terrain.select('slope').rename('Slope')

    # Fire memory MODIS
    startMemoryDate = ee.Date.fromYMD(currentYear.subtract(5), 1, 1)
    endMemoryDate = ee.Date.fromYMD(currentYear, 1, 1)

    modisMemoryCol = (ee.ImageCollection('MODIS/061/MCD64A1')
                      .filterDate(startMemoryDate, endMemoryDate)
                      .filterBounds(amazonBounds)
                      .select('BurnDate'))

    fireMemory = modisMemoryCol.max().gt(0).unmask(0).rename('Fire_Memory_5y')

    # Fusion
    imageFinale = (inputs.addBands(target)
        .addBands(oniImagePrevYear)
        .addBands(oniImageCurrentYear)
        .addBands(distanceStrictProtectedAreas)
        .addBands(distanceSustainableUseProtectedAreas)
        .addBands(distanceAllProtectedAreas)
        .addBands(distanceAuxZonesHumaines)
        .addBands(etSafe)
        .addBands(recentDeforestation)
        .addBands(windSpeed)
        .addBands(population)
        .addBands(nightLights)
        .addBands(elevation)
        .addBands(slope)
        .addBands(fireMemory))

    return imageFinale, target