# -*- coding: utf-8 -*-
"""RF_TrainingSet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMMv-0UCJ06BAX91BRkgBOAtvGodXB-Y
"""

#Training Set

import ee
from inputBands_Generator import create_inputBands
ee.Authenticate()
ee.Initialize(project='macedo-lab-general-9051')
area = ee.FeatureCollection('projects/ksolvik-misc/assets/Lim_Raisg')
amazonBounds = area.geometry().simplify(1000) #I had to simplify the area because stratified sampling was failing on the initial complex area

startYears = ee.List([2019, 2020, 2021, 2022, 2023]) #We have to select the correct years when training the model to avoid data leackage

# I changed the two sampling methods to one unique stratified sampling, it worked for 100 & 1000 points per year
def extractPointsForYear(year):
    targetYear = ee.Number(year)

    imageFinale, target = create_inputBands(year)

    #Stratify only on the modis binary map otherwise it is computationnaly too heavy
    finalPoints = imageFinale.stratifiedSample(
        numPoints=100,
        classBand='class',
        region=amazonBounds,
        scale=500,
        seed=targetYear,
        geometries=True,
        tileScale=16)


    return finalPoints.map(lambda f: f.set('year', targetYear))


# Extraction loop
listDeCollections = startYears.map(lambda year: extractPointsForYear(year))
allTrainingPoints = ee.FeatureCollection(listDeCollections).flatten()

# EXPORT
task = ee.batch.Export.table.toAsset(
    collection=allTrainingPoints,
    description='Amazon_TrainingSet',
    assetId='projects/columbia-research-project/assets/TrainingSet' #Feel free to change the name
)

task.start()

