# -*- coding: utf-8 -*-
"""RF_ValidationSet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1koep8a2WG3h8aSpgMfwsjwfBo3KKugHH
"""

#Validation Set

import ee
from inputBands_Generator import create_inputBands
ee.Authenticate()
ee.Initialize(project='macedo-lab-general-9051')
area = ee.FeatureCollection('projects/ksolvik-misc/assets/Lim_Raisg')
amazonBounds = area.geometry().simplify(1000)

startYears = ee.List([2019, 2020, 2021, 2022, 2023, 2024)

def extractPointsForYear(year):
    targetYear = ee.Number(year)

    imageFinale, target = create_inputBands(year)

    finalPoints = imageFinale.sample(
        region=amazonBounds,
        scale=500,
        numPixels=10000,
        geometries=True
    )

    return finalPoints.map(lambda f: f.set('year', targetYear))


# Extraction loop
listDeCollections = startYears.map(lambda year: extractPointsForYear(year))
allTrainingPoints = ee.FeatureCollection(listDeCollections).flatten()

# EXPORT
task = ee.batch.Export.table.toAsset(
    collection=allTrainingPoints,
    description='Amazon_ValidationSet',
    assetId='projects/columbia-research-project/assets/ValidationSet' #Feel free to change the name
)

task.start()

